### ISSUE TITLE
Push Popup

### ISSUE THREAD

**Issue by TimUntersberger** [NeogitOrg/neogit#13]
### Actions
- [x] Push to pushremote
- [x] Push to upstream
- [x] Push to branch

**Comment by tomaskallup** [comment]
Ah I was wondering why the push isn't working at all, is this something I could perhaps help with? This seems to be open for quite some time and for me even the `pushremote` isn't working.

**Comment by RianFuro** [comment]
Totally agree; as I said, pretty bare bones :sweat_smile:

**Comment by itmecho** [comment]
> We do want to take over the upstream/pushremote distinction from magit and some prompts to dynamically set the upstream when necessary are definitely needed

Am I right in thinking this would allow you to create a new local branch and then push it up to remote when it doesn't exist? i.e.`git checkout -b my-new-branch && git push --set-upstream origin my-new-branch`

At the moment I create the branch with neogit but then run the `git push` manually

**Comment by TimUntersberger** [comment]
@itmecho no it would use the upstream but not set it up. Tbh I also think the current implementation is a bit annoying, but I don't really know how to do this correctly yet.

**Comment by itmecho** [comment]
Hmm I was trying to think of how I would do it. Best I came up with was a new option in the push popup for "push and set upstream", then prompt for the remote name (or if there is only one just use that) and then prompt for the remote branch name (which could pre-populate with the current branch name). Those could also be set as defaults in the config.

That's just my use case though, not sure how it would fit in with other people's =\

**Comment by itmecho** [comment]
Hacky version which "worked on my machine"

https://github.com/TimUntersberger/neogit/compare/master...itmecho:proto/set-upstream

**Comment by TimUntersberger** [comment]
@itmecho I added a switch to the push popup in #131.

**Comment by DemonInTheCloset** [comment]
Hi, I am not sure if I should say this here, but could you add a `--tags` flag for the push popup?

**Comment by mcepl** [comment]
For explanation why there are two https://magit.vc/manual/magit.html#The-Two-Remotes but still doesn’t make sense to me. IMHO, feature branch should never know what its final destination will be and should only be push to `my-fork/feature`. Whole merging (be it done with pull/merge-requests or via `git send-email`) should be outside of the local git operations.

**Comment by practicalli-john** [comment]
I work on many open source projects and set the origin name to the GitHub organisation or user account name, so I know where I am pushing too

It would be very useful to set where neogit pushes to when using `p` from the push menu

Currently I use `e` for elsewhere and type in the origin name I use for that repository.  

I assume the value of the origin can be ascertained from the local Git repository.

**Comment by CKolkey** [comment]
Agreed! I'll be upstreaming some changes that should solve for this with some ability to set git config values

<img width="505" alt="Screenshot 2023-05-06 at 21 04 14" src="https://user-images.githubusercontent.com/7228095/236642214-56bdc3a5-6e61-43c0-ae5f-acc4f2e2c638.png">

**Comment by ten3roberts** [comment]
> 

Not knowing what you're force pushing to is part of the fun, especially when reviewing pull requests.

Jokes aside, as @CKolkey mentioned we are soon to upstream a *lot* of QOL improvements to neogit which will for example include better push.
