### ISSUE TITLE
Log Popup

### ISSUE THREAD

**Issue by TimUntersberger** [NeogitOrg/neogit#16]
### Actions

- [x] Log current
- [x] Log other
- [x] Log HEAD
- [x] Log local branches
- [x] Log all branches
- [x] Log all references
- [x] Reflog current
- [x] Reflog other
- [x] Reflog HEAD

**Comment by treeman** [comment]
`--` to "Limit to files" (used to be `=f` in older versions of magit) would be great to have.

**Comment by GCBallesteros** [comment]
After running a log command a new buffer opens with the relevant commits. One can then press <cr> on them to open the diffs. The start of a typical diff view of the commit would look like:

```
Commit b2f7d0e9bc541e6626ee2c06f5e8a525e3ae6614

Author:     Cameron <Alleyria@gmail.com>
AuthorDate: Sat Oct 7 16:22:39 2023 +0200
Committer:  Cameron <Alleyria@gmail.com>
CommitDate: Tue Oct 31 21:58:19 2023 +0100

Use popup mappings defined by user for all buffers

3 files changed, 47 insertions(+), 47 deletions(-)
 lua/neogit/buffers/commit_view/init.lua | 12 +++++----- << pressing <cr> while on this lines jumps 
lua/neogit/buffers/log_view/init.lua    | 40 +++++++++++++++----------------
lua/neogit/buffers/reflog_view/init.lua | 42 ++++++++++++++++-----------------

... the diffs
```

It would be nice to be able to press <cr> again while on top of one of the lines shown on the start of the commit to jump to the relevant part of commit.
