### ISSUE TITLE
Status Buffer

### ISSUE THREAD

**Issue by TimUntersberger** [NeogitOrg/neogit#18]
### Actions

- [x] Stage file
- [x] Stage hunk
- [x] Stage selection
- [x] Stage unstaged changes
- [x] Stage everything (includes untracked files)
- [x] Unstage file
- [x] Unstage hunk
- [x] Unstage selection
- [x] Unstage staged changes
- [x] Toggle diff 
  - [x] Modified files
  - [x] New files
  - [x] Deleted files
- [x] Go to file
- [x] Change foldlevel
- [x] Restore file
- [x] Restore hunk
- [x] Restore selection

**Comment by matharman** [comment]
Would it be possible to support discarding visual selection with `x` the way the visual staging is supported? Sometimes for diffs like stray whitespace I would like to keep parts of a hunk, and discard only certain lines of the hunk.

**Comment by itmecho** [comment]
> Would it be possible to support discarding visual selection with `x` the way the visual staging is supported? Sometimes for diffs like stray whitespace I would like to keep parts of a hunk, and discard only certain lines of the hunk.

I thought this already worked? I'm sure I've used it but I'll double check when I get to work

**Comment by matharman** [comment]
> I thought this already worked? I'm sure I've used it but I'll double check when I get to work

I set up a test repository with just one file to try this again, and it worked fine. It must be a problem with the particular repo's gitconfig that I was working in yesterday, as some git command return status 128.

I'll investigate further and come back with a new issue if I find something I can't resolve.

**Comment by armincerf** [comment]
Is it possible to discard all Unstaged/Staged files if you have the cursor on 'Unstaged changes' and press `x`? This works in magit but is currently missing from Neogit. Alternatively, allowing x to discard a visual selection (of files, not hunks) would also solve this.

The use case is sometimes I have a lot of changes and just want to get rid of them all, and it's tedious to do them one at a time.

**Comment by CKolkey** [comment]
I believe all features are implemented, including visual selection of multiple files, or discarding a part of a file.
